# Generated by Django 5.1.1 on 2024-10-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudante",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=150)),
                ("email", models.TextField(max_length=150)),
                ("data_nascimento", models.DateField()),
                ("senha", models.TextField(max_length=50)),
            ],
        ),
    ]
